# Video Source Configuration
video_source:
  use_youtube_search: true  # Set to false to use manual video input
  max_youtube_results: 5    # Number of YouTube videos to search for
  prompt: f1 racing clips              # Optional: Set search prompt or video paths here
  audio_file: /Users/leoasatoorian/Documents/UP.wav         # Optional: Set path to audio file

# Video Processing
video_processing:
  fontsize: 24             # Font size for lyrics overlay
  text_color: "white"      # Color of lyrics text
  text_position: "bottom"  # Position of lyrics overlay

# Output Configuration
output:
  music_video_filename: "generated_music_video.mp4"
  final_video_filename: "final_video.mp4" 